# Docker compose file for local testing
services:
  # The Mariadb database
  # login with root:root
  mariadb:
    image: mariadb:latest@sha256:dd9b303aed4f4890ed09f766d8ca9ddfd176c0c6f6267feff53b3192ec65a979
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
