[metadata]
version = "1.0"

[versions]
# platforms
kotlin = "1.8.20"
java = "17"
mindustry = "144"

# libraries
distributor = "3.0.0"
junit = "5.9.0"

# gradle plugins
toxopid = "3.2.0"
indra = "3.1.1"
spotless = "6.19.0"
shadow = "7.1.2"
klint = "0.49.1"

[libraries]
# libraries
distributor-api = { module = "fr.xpdustry:distributor-api", version.ref = "distributor" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

# gradle plugins
toxopid = { module = "fr.xpdustry:toxopid", version.ref = "toxopid" }
indra-common = { module = "net.kyori:indra-common", version.ref = "indra" }
indra-licenser-spotless = { module = "net.kyori:indra-licenser-spotless", version.ref = "indra" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
shadow = { module = "gradle.plugin.com.github.johnrengelman:shadow", version.ref = "shadow" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
