[metadata]
version = "1.0"

[versions]
# platforms
kotlin-core = "1.9.0"
kotlin-coroutine = "1.7.3"
kotlin-runtime = "3.0.0"
java = "17"
mindustry = "145"

# libraries
distributor = "3.1.0"
junit = "5.9.0"
testcontainers = "1.18.3"
mongodb = "4.10.1"
guava = "32.0.1-jre"
gson = "2.10.1"
hoplite = "2.7.4"
reactor-core = "3.5.6"
deepl = "1.3.0"
slf4j = "2.0.7"
discord4j = "3.2.4"
password4j = "1.7.1"
kryo = "5.5.0"
rabbitmq-client = "5.17.0"
jsoup = "1.16.1"
minio = "8.5.4"
javacord = "3.8.0"
log4j-to-slf4j = "2.20.0"

# gradle plugins
toxopid = "3.2.0"
indra = "3.1.1"
spotless = "6.19.0"
shadow = "8.1.1"
ktlint = "0.49.1"
gradle-versions = "0.47.0"

[libraries]
# libraries
distributor-api = { module = "fr.xpdustry:distributor-api", version.ref = "distributor" }
distributor-kotlin = { module = "fr.xpdustry:distributor-kotlin", version.ref = "distributor" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-mongodb = { module = "org.testcontainers:mongodb", version.ref = "testcontainers" }
testcontainers-rabbitmq = { module = "org.testcontainers:rabbitmq", version.ref = "testcontainers" }
mongodb-driver-reactive = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "mongodb" }
mongodb-driver-kotlin-coroutine = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "mongodb" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
reactor-core = { module = "io.projectreactor:reactor-core", version.ref = "reactor-core" }
reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "reactor-core" }
hoplite-core = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
hoplite-yaml = { module = "com.sksamuel.hoplite:hoplite-yaml", version.ref = "hoplite" }
deepl = { module = "com.deepl.api:deepl-java", version.ref = "deepl" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
discord4j-core = { module = "com.discord4j:discord4j-core", version.ref = "discord4j" }
password4j = { module = "com.password4j:password4j", version.ref = "password4j" }
kryo = { module = "com.esotericsoftware:kryo", version.ref = "kryo" }
rabbitmq-client = { module = "com.rabbitmq:amqp-client", version.ref = "rabbitmq-client" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
minio = { module = "io.minio:minio", version.ref = "minio" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutine" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutine" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlin-coroutine" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlin-coroutine" }
javacord-api = { module = "org.javacord:javacord-api", version.ref = "javacord" }
javacord-core = { module = "org.javacord:javacord-core", version.ref = "javacord" }
log4j-to-slf4j = { module = "org.apache.logging.log4j:log4j-to-slf4j", version.ref = "log4j-to-slf4j" }

# gradle plugins
toxopid = { module = "fr.xpdustry:toxopid", version.ref = "toxopid" }
indra-common = { module = "net.kyori:indra-common", version.ref = "indra" }
indra-licenser-spotless = { module = "net.kyori:indra-licenser-spotless", version.ref = "indra" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
shadow = { module = "com.github.johnrengelman:shadow", version.ref = "shadow" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
gradle-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradle-versions" }
